---
- name: set kernel.panic to 10
  sysctl:
    name: kernel.panic
    value: 10
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: disable ipv4 lo.accept_source_route
  sysctl:
    name: net.ipv4.conf.lo.accept_source_route
    value: 0
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: disble ipv4 send_redirects
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: disable ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_file: /etc/sysctl.conf
    reload: yes
